[0.000000] (-) TimerEvent: {}
[0.000975] (-) JobUnselected: {'identifier': 'camera_feed_pub'}
[0.001046] (-) JobUnselected: {'identifier': 'drone_control_pkg'}
[0.001114] (-) JobUnselected: {'identifier': 'libmavconn'}
[0.001146] (-) JobUnselected: {'identifier': 'mavlink'}
[0.001261] (-) JobUnselected: {'identifier': 'mavros'}
[0.001277] (-) JobUnselected: {'identifier': 'mavros_extras'}
[0.001291] (-) JobUnselected: {'identifier': 'mavros_msgs'}
[0.001305] (-) JobUnselected: {'identifier': 'orbslam_pub'}
[0.001322] (py_img_sub) JobQueued: {'identifier': 'py_img_sub', 'dependencies': OrderedDict()}
[0.001343] (py_img_sub) JobStarted: {'identifier': 'py_img_sub'}
[0.100076] (-) TimerEvent: {}
[0.200451] (-) TimerEvent: {}
[0.289778] (py_img_sub) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 51, in build\n    setup_py_data = get_setup_data(self.context.pkg, env)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/__init__.py", line 20, in get_setup_data\n    return dict(pkg.metadata[key](env))\n  File "/usr/lib/python3/dist-packages/colcon_ros/package_augmentation/ros_ament_python.py", line 57, in getter\n    return get_setup_information(\n  File "/usr/lib/python3/dist-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 249, in get_setup_information\n    _setup_information_cache[hashable_env] = _get_setup_information(\n  File "/usr/lib/python3/dist-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 296, in _get_setup_information\n    result = subprocess.run(\n  File "/usr/lib/python3.10/subprocess.py", line 526, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/python3\', \'-c\', \'import sys;from contextlib import suppress;exec("with suppress(ImportError):    from setuptools.extern.packaging.specifiers    import SpecifierSet");exec("with suppress(ImportError):    from packaging.specifiers import SpecifierSet");from distutils.core import run_setup;dist = run_setup(    \\\'setup.py\\\', script_args=(\\\'--dry-run\\\',), stop_after=\\\'config\\\');skip_keys = (\\\'cmdclass\\\', \\\'distclass\\\', \\\'ext_modules\\\', \\\'metadata\\\');data = {    key: value for key, value in dist.__dict__.items()     if (        not key.startswith(\\\'_\\\') and         not callable(value) and         key not in skip_keys and         key not in dist.display_option_names    )};data[\\\'metadata\\\'] = {    k: v for k, v in dist.metadata.__dict__.items()     if k not in (\\\'license_files\\\', \\\'provides_extras\\\')};sys.stdout.buffer.write(repr(data).encode(\\\'utf-8\\\'))\']\' returned non-zero exit status 1.\n'}
[0.290191] (py_img_sub) JobEnded: {'identifier': 'py_img_sub', 'rc': 1}
[0.300214] (-) EventReactorShutdown: {}
